language: c
compiler:
  - clang
  - gcc
os:
  - osx
before_install:
  - brew update
  - brew install sdl2 sdl2_image
  - brew uninstall icu4c && brew install icu4c
  - brew link --force icu4c 
script: 
  - mkdir build
  - cd build
  - cmake ../ && make
