language: c
compiler:
  - clang
  - gcc
os:
  - osx
before_install:
  - brew update
  - brew install sdl2 sdl2_image 
script: 
  - mkdir build
  - cd build
  - CMAKE_PREFIX_PATH=/usr/local/Cellar/icu4c/62.1 cmake ../ && make
